# Generated by Django 5.0.4 on 2024-04-19 07:34

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='MaLopHoc',
            field=models.CharField(default=classroom.models.generate_class_code, max_length=10, primary_key=True, serialize=False),
        ),
    ]
