# Generated by Django 5.0.1 on 2024-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('MaSinhVien', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoVaTen', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('TenKhoa', models.CharField(max_length=50)),
                ('SDT', models.CharField(max_length=10)),
            ],
        ),
    ]
