# Generated by Django 5.0.4 on 2024-04-19 07:34

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='MaGiangVien',
            field=models.CharField(default=teacher.models.generate_teacher_code, max_length=10, primary_key=True, serialize=False),
        ),
    ]
