version: '3.9'

services:
  backend:
    build:
      context: ./BE_PTUD
    container_name: backend
    command: /venv/bin/uvicorn BE_PTUD.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - ./BE_PTUD:/app
    ports:
      - "8000:8000"

  # frontend:
  #   build:
  #     context: ./FE_PTUD
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./FE_PTUD:/app