# Generated by Django 5.0.1 on 2024-04-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenThanhPhanDiem', models.CharField(max_length=50)),
                ('Diem', models.FloatField()),
                ('MaLopHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('MaSinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'unique_together': {('MaSinhVien', 'MaLopHoc', 'TenThanhPhanDiem')},
            },
        ),
    ]
