# Generated by Django 5.0.1 on 2024-04-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('MaMonHoc', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenMonHoc', models.CharField(max_length=50)),
                ('SoTinChi', models.IntegerField()),
            ],
        ),
    ]
