# Generated by Django 5.0.4 on 2024-04-19 07:34

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_class_student_magiangvien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='MaSinhVien',
            field=models.CharField(default=student.models.generate_student_code, max_length=10, primary_key=True, serialize=False),
        ),
    ]
